// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


// Edited to move THING_ID to file "arduino_secrets.h" (which is in .gitignore)
const char THING_ID[] = SECRET_ID;

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onRelay2Change();
void onLightChange();
void onUpdateDisplayChange();
void onRgbColorChange();

bool relay_2;
float humidity;
int light;
float temperature;
int moistValue;
bool updateDisplay;
bool relay_1;
CloudColoredLight rgbColor;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(relay_2, READWRITE, ON_CHANGE, onRelay2Change, 1);
  ArduinoCloud.addProperty(humidity, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(light, READWRITE, 1 * SECONDS, onLightChange);
  ArduinoCloud.addProperty(temperature, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(moistValue, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(updateDisplay, READWRITE, ON_CHANGE, onUpdateDisplayChange);
  ArduinoCloud.addProperty(relay_1, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(rgbColor, READWRITE, ON_CHANGE, onRgbColorChange, 1);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
