// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

// Edited to move THING_ID to file "arduino_secrets.h" (which is in .gitignore)
const char THING_ID[] = SECRET_ID;

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onTargetMoistureChange();
void onWaterPumpActivateChange();

int target_moisture;
bool waterPump_activate;
int moisture;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(target_moisture, READWRITE, ON_CHANGE, onTargetMoistureChange);
  ArduinoCloud.addProperty(waterPump_activate, READWRITE, ON_CHANGE, onWaterPumpActivateChange);
  ArduinoCloud.addProperty(moisture, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
